import os
import zipfile

# List of all relative file paths from the folder structure
files = [
    "network-infrastructure/switched-campus/switch-administration/managing-mac-address-table.md",
    "network-infrastructure/switched-campus/switch-administration/errdisable-recovery.md",
    "network-infrastructure/switched-campus/switch-administration/l2-mtu.md",
    "network-infrastructure/switched-campus/layer-2-protocols/cdp-lldp.md",
    "network-infrastructure/switched-campus/layer-2-protocols/udld.md",
    "network-infrastructure/switched-campus/vlan-technologies/access-ports.md",
    "network-infrastructure/switched-campus/vlan-technologies/trunk-ports.md",
    "network-infrastructure/switched-campus/vlan-technologies/native-vlan.md",
    "network-infrastructure/switched-campus/vlan-technologies/manual-vlan-pruning.md",
    "network-infrastructure/switched-campus/vlan-technologies/normal-range-and-extended-range-vlans.md",
    "network-infrastructure/switched-campus/vlan-technologies/voice-vlan.md",
    "network-infrastructure/switched-campus/etherchannel/lacp-static.md",
    "network-infrastructure/switched-campus/etherchannel/layer-2-layer-3.md",
    "network-infrastructure/switched-campus/etherchannel/load-balancing.md",
    "network-infrastructure/switched-campus/etherchannel/etherchannel-misconfiguration-guard.md",
    "network-infrastructure/switched-campus/etherchannel/identify-multichassis-etherchannel-use-cases.md",
    "network-infrastructure/switched-campus/spanning-tree-protocol/pvst-rapid-pvst-mst.md",
    "network-infrastructure/switched-campus/spanning-tree-protocol/switch-priority-port-priority-tuning-port-path-cost-stp-timers.md",
    "network-infrastructure/switched-campus/spanning-tree-protocol/portfast-bpdu-guard-bpdu-filter.md",
    "network-infrastructure/switched-campus/spanning-tree-protocol/loop-guard-root-guard.md",
    "network-infrastructure/routing-concepts/administrative-distance.md",
    "network-infrastructure/routing-concepts/static-routing.md",
    "network-infrastructure/routing-concepts/policy-based-routing.md",
    "network-infrastructure/routing-concepts/vrf-lite.md",
    "network-infrastructure/routing-concepts/vrf-aware-routing.md",
    "network-infrastructure/routing-concepts/route-leaking.md",
    "network-infrastructure/routing-concepts/route-filtering.md",
    "network-infrastructure/routing-concepts/redistribution.md",
    "network-infrastructure/routing-concepts/routing-protocol-authentication.md",
    "network-infrastructure/routing-concepts/bidirectional-forwarding-detection.md",
    "network-infrastructure/routing-concepts/l3-mtu.md",
    "network-infrastructure/eigrp/adjacencies.md",
    "network-infrastructure/eigrp/best-path-selection/feasibility.md",
    "network-infrastructure/eigrp/best-path-selection/classic-and-wide-metrics.md",
    "network-infrastructure/eigrp/operations/general-operations.md",
    "network-infrastructure/eigrp/operations/topology-table.md",
    "network-infrastructure/eigrp/operations/packet-types.md",
    "network-infrastructure/eigrp/operations/stuck-in-active.md",
    "network-infrastructure/eigrp/operations/graceful-shutdown.md",
    "network-infrastructure/eigrp/eigrp-named-mode.md",
    "network-infrastructure/eigrp/optimization-convergence-scalability/query-propagation-boundaries.md",
    "network-infrastructure/eigrp/optimization-convergence-scalability/leak-map-with-summary-routes.md",
    "network-infrastructure/eigrp/optimization-convergence-scalability/eigrp-stub-with-leak-map.md",
    "network-infrastructure/ospf/adjacencies.md",
    "network-infrastructure/ospf/ospfv3-address-family-support.md",
    "network-infrastructure/ospf/network-types-area-types.md",
    "network-infrastructure/ospf/path-preference.md",
    "network-infrastructure/ospf/operations/general-operations.md",
    "network-infrastructure/ospf/operations/graceful-shutdown.md",
    "network-infrastructure/ospf/operations/gtsm.md",
    "network-infrastructure/ospf/optimization-convergence-scalability/metrics.md",
    "network-infrastructure/ospf/optimization-convergence-scalability/lsa-throttling-spf-tuning.md",
    "network-infrastructure/ospf/optimization-convergence-scalability/stub-router.md",
    "network-infrastructure/ospf/optimization-convergence-scalability/prefix-suppression.md",
    "network-infrastructure/bgp/ibgp-ebgp-peer-relations/peer-groups-templates.md",
    "network-infrastructure/bgp/ibgp-ebgp-peer-relations/active-passive.md",
    "network-infrastructure/bgp/ibgp-ebgp-peer-relations/timers.md",
    "network-infrastructure/bgp/ibgp-ebgp-peer-relations/dynamic-neighbors.md",
    "network-infrastructure/bgp/ibgp-ebgp-peer-relations/four-byte-as-numbers.md",
    "network-infrastructure/bgp/ibgp-ebgp-peer-relations/private-as-numbers.md",
    "network-infrastructure/bgp/path-selection/attributes.md",
    "network-infrastructure/bgp/path-selection/best-path-selection-algorithm.md",
    "network-infrastructure/bgp/path-selection/load-balancing.md",
    "network-infrastructure/bgp/routing-policies/attribute-manipulation.md",
    "network-infrastructure/bgp/routing-policies/conditional-advertisement.md",
    "network-infrastructure/bgp/routing-policies/outbound-route-filtering.md",
    "network-infrastructure/bgp/routing-policies/standard-and-extended-communities.md",
    "network-infrastructure/bgp/routing-policies/multihoming.md",
    "network-infrastructure/bgp/as-path-manipulations/local-as-allowas-in-remove-private-as.md",
    "network-infrastructure/bgp/as-path-manipulations/as-path-prepending.md",
    "network-infrastructure/bgp/as-path-manipulations/regular-expressions.md",
    "network-infrastructure/bgp/convergence-scalability/route-reflectors.md",
    "network-infrastructure/bgp/convergence-scalability/aggregation-as-set.md",
    "network-infrastructure/bgp/other-bgp-features.md",
    "network-infrastructure/multicast/layer-2-multicast/igmpv2-igmpv3.md",
    "network-infrastructure/multicast/layer-2-multicast/igmp-snooping-pim-snooping.md",
    "network-infrastructure/multicast/layer-2-multicast/igmp-querier.md",
    "network-infrastructure/multicast/layer-2-multicast/igmp-filter.md",
    "network-infrastructure/multicast/layer-2-multicast/mld.md",
    "network-infrastructure/multicast/reverse-path-forwarding-check.md",
    "network-infrastructure/multicast/pim/sparse-mode.md",
    "network-infrastructure/multicast/pim/static-rp-bsr-auto-rp.md",
    "network-infrastructure/multicast/pim/group-to-rp-mapping.md",
    "network-infrastructure/multicast/pim/source-specific-multicast.md",
    "network-infrastructure/multicast/pim/multicast-boundary-rp-announcement-filter.md",
    "network-infrastructure/multicast/pim/pimv6-anycast-rp.md",
    "network-infrastructure/multicast/pim/ipv4-anycast-rp-using-msdp.md",
    "network-infrastructure/multicast/pim/multicast-multipath.md",
    "software-defined-infrastructure/cisco-sd-access/underlay/manual.md",
    "software-defined-infrastructure/cisco-sd-access/underlay/lan-automation-pnp.md",
    "software-defined-infrastructure/cisco-sd-access/underlay/device-discovery-and-device-management.md",
    "software-defined-infrastructure/cisco-sd-access/underlay/extended-nodes-policy-extended-nodes.md",
    "software-defined-infrastructure/cisco-sd-access/overlay/lisp-bgp-control-planes.md",
    "software-defined-infrastructure/cisco-sd-access/overlay/vxlan-data-plane.md",
    "software-defined-infrastructure/cisco-sd-access/overlay/cisco-trustsec-policy-plane.md",
    "software-defined-infrastructure/cisco-sd-access/overlay/l2-flooding.md",
    "software-defined-infrastructure/cisco-sd-access/overlay/native-multicast.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-design/single-site-campus.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-design/multisite.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-design/fabric-in-a-box.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-deployment/host-onboarding.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-deployment/authentication-templates.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-deployment/port-configuration.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-deployment/multisite-remote-border.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-deployment/border-priority.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-deployment/adding-devices-to-fabric.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-border-handoff/sda-sdwan-ip-transits.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-border-handoff/peer-device-fusion-router.md",
    "software-defined-infrastructure/cisco-sd-access/fabric-border-handoff/layer-2-border-handoff.md",
    "software-defined-infrastructure/cisco-sd-access/segmentation/macro-segmentation-using-virtual-networks.md",
    "software-defined-infrastructure/cisco-sd-access/segmentation/micro-level-segmentation-using-sgts-and-sgacls.md",
    "software-defined-infrastructure/cisco-sd-wan/controller-architecture/management-plane-vmanage.md",
    "software-defined-infrastructure/cisco-sd-wan/controller-architecture/orchestration-plane-vbond.md",
    "software-defined-infrastructure/cisco-sd-wan/controller-architecture/control-plane-vsmart.md",
    "software-defined-infrastructure/cisco-sd-wan/sd-wan-underlay/wan-cloud-edge-deployment-aws-azure-google-cloud.md",
    "software-defined-infrastructure/cisco-sd-wan/sd-wan-underlay/wan-edge-deployment-hardware.md",
    "software-defined-infrastructure/cisco-sd-wan/sd-wan-underlay/greenfield-brownfield-hybrid-deployments.md",
    "software-defined-infrastructure/cisco-sd-wan/sd-wan-underlay/system-configuration-system-ip-site-id-org-name-vbond-address.md",
    "software-defined-infrastructure/cisco-sd-wan/sd-wan-underlay/transport-configuration-underlay-tunnel-interfaces-allowed-services-tloc-extension.md",
    "software-defined-infrastructure/cisco-sd-wan/overlay-management-protocol/omp-attributes.md",
    "software-defined-infrastructure/cisco-sd-wan/overlay-management-protocol/ipsec-key-management.md",
    "software-defined-infrastructure/cisco-sd-wan/overlay-management-protocol/route-aggregation.md",
    "software-defined-infrastructure/cisco-sd-wan/overlay-management-protocol/redistribution.md",
    "software-defined-infrastructure/cisco-sd-wan/overlay-management-protocol/additional-features-bgp-as-path-propagation-sda-integration.md",
    "software-defined-infrastructure/cisco-sd-wan/configuration-templates/cli-templates.md",
    "software-defined-infrastructure/cisco-sd-wan/configuration-templates/feature-templates.md",
    "software-defined-infrastructure/cisco-sd-wan/configuration-templates/device-templates.md",
    "software-defined-infrastructure/cisco-sd-wan/centralized-policies/data-policies.md",
    "software-defined-infrastructure/cisco-sd-wan/centralized-policies/application-aware-routing-policies.md",
    "software-defined-infrastructure/cisco-sd-wan/centralized-policies/control-policies.md",
    "software-defined-infrastructure/cisco-sd-wan/localized-policies/access-lists.md",
    "software-defined-infrastructure/cisco-sd-wan/localized-policies/route-policies.md",
    "transport-technologies-and-solutions/static-point-to-point-gre-tunnels.md",
    "transport-technologies-and-solutions/mpls/operations/label-stack-lsr-lsp.md",
    "transport-technologies-and-solutions/mpls/operations/ldp.md",
    "transport-technologies-and-solutions/mpls/operations/mpls-ping-mpls-traceroute.md",
    "transport-technologies-and-solutions/mpls/l3vpn/pe-ce-routing-using-bgp.md",
    "transport-technologies-and-solutions/mpls/l3vpn/basic-mp-bgp-vpnv4-vpnv6.md",
    "transport-technologies-and-solutions/dmvpn/troubleshoot-dmvpn-phase-3-with-dual-hub/nhrp.md",
    "transport-technologies-and-solutions/dmvpn/troubleshoot-dmvpn-phase-3-with-dual-hub/ipsec-ikev2-using-preshared-key.md",
    "infrastructure-security-and-services/device-security-on-cisco-ios-xe/control-plane-policing-and-protection.md",
    "infrastructure-security-and-services/device-security-on-cisco-ios-xe/aaa.md",
    "infrastructure-security-and-services/network-security/switch-security-features/vacl-pacl.md",
    "infrastructure-security-and-services/network-security/switch-security-features/storm-control.md",
    "infrastructure-security-and-services/network-security/switch-security-features/dhcp-snooping-dhcp-option-82.md",
    "infrastructure-security-and-services/network-security/switch-security-features/ip-source-guard.md",
    "infrastructure-security-and-services/network-security/switch-security-features/dynamic-arp-inspection.md",
    "infrastructure-security-and-services/network-security/switch-security-features/port-security.md",
    "infrastructure-security-and-services/network-security/router-security-features/ipv6-traffic-filters.md",
    "infrastructure-security-and-services/network-security/router-security-features/ipv4-access-control-lists.md",
    "infrastructure-security-and-services/network-security/router-security-features/unicast-reverse-path-forwarding.md",
    "infrastructure-security-and-services/network-security/ipv6-infrastructure-security-features/ra-guard.md",
    "infrastructure-security-and-services/network-security/ipv6-infrastructure-security-features/dhcp-guard.md",
    "infrastructure-security-and-services/network-security/ipv6-infrastructure-security-features/binding-table.md",
    "infrastructure-security-and-services/network-security/ipv6-infrastructure-security-features/device-tracking.md",
    "infrastructure-security-and-services/network-security/ipv6-infrastructure-security-features/nd-inspection-snooping.md",
    "infrastructure-security-and-services/network-security/ipv6-infrastructure-security-features/source-guard.md",
    "infrastructure-security-and-services/system-management/device-management/console-vty.md",
    "infrastructure-security-and-services/system-management/device-management/ssh-scp.md",
    "infrastructure-security-and-services/system-management/device-management/restconf-netconf.md",
    "infrastructure-security-and-services/system-management/snmp-v2c-v3.md",
    "infrastructure-security-and-services/system-management/logging/local-logging-syslog-debugs-conditional-debugs.md",
    "infrastructure-security-and-services/system-management/logging/configuration-change-notification-logging.md",
    "infrastructure-security-and-services/system-management/logging/timestamps.md",
    "infrastructure-security-and-services/quality-of-service/differentiated-services-architecture.md",
    "infrastructure-security-and-services/quality-of-service/classification-trust-boundary.md",
    "infrastructure-security-and-services/quality-of-service/network-based-application-recognition-nbar.md",
    "infrastructure-security-and-services/quality-of-service/marking-dscp-values-in-ipv4-ipv6-headers.md",
    "infrastructure-security-and-services/quality-of-service/policing-shaping.md",
    "infrastructure-security-and-services/quality-of-service/congestion-management-avoidance.md",
    "infrastructure-security-and-services/quality-of-service/hqos.md",
    "infrastructure-security-and-services/quality-of-service/end-to-end-layer-3-qos-using-mqc.md",
    "infrastructure-security-and-services/network-services/first-hop-redundancy-protocols/hsrp-vrrp.md",
    "infrastructure-security-and-services/network-services/first-hop-redundancy-protocols/redundancy-using-ipv6-rs-ra.md",
    "infrastructure-security-and-services/network-services/time-synchronization-protocols/ntp-as-a-client.md",
    "infrastructure-security-and-services/network-services/time-synchronization-protocols/ptp-design-considerations.md",
    "infrastructure-security-and-services/network-services/dhcp-on-cisco-devices/client-server-relay.md",
    "infrastructure-security-and-services/network-services/dhcp-on-cisco-devices/options.md",
    "infrastructure-security-and-services/network-services/dhcp-on-cisco-devices/slaac-dhcpv6-integration.md",
    "infrastructure-security-and-services/network-services/dhcp-on-cisco-devices/stateful-stateless-dhcpv6.md",
    "infrastructure-security-and-services/network-services/dhcp-on-cisco-devices/dhcpv6-prefix-delegation.md",
    "infrastructure-security-and-services/network-services/ipv4-network-address-translation/static-nat-pat.md",
    "infrastructure-security-and-services/network-services/ipv4-network-address-translation/dynamic-nat-pat.md",
    "infrastructure-security-and-services/network-services/ipv4-network-address-translation/policy-based-nat-pat.md",
    "infrastructure-security-and-services/network-services/ipv4-network-address-translation/vrf-aware-nat-pat.md",
    "infrastructure-security-and-services/network-services/ipv4-network-address-translation/vrf-aware-software-infrastructure-vasi-nat.md",
    "infrastructure-security-and-services/network-optimization/ip-sla-icmp-udp-tcp-probes.md",
    "infrastructure-security-and-services/network-optimization/tracking-objects-lists.md",
    "infrastructure-security-and-services/network-optimization/flexible-netflow.md",
    "infrastructure-security-and-services/network-operations/traffic-capture/span-rspan-erspan.md",
    "infrastructure-security-and-services/network-operations/traffic-capture/embedded-packet-capture.md",
    "infrastructure-security-and-services/network-operations/troubleshooting-tools/data-path-packet-trace.md",
    "infrastructure-security-and-services/network-operations/troubleshooting-tools/conditional-debugger-debug-platform-condition.md",
    "infrastructure-automation-and-programmability/data-encoding-formats/json.md",
    "infrastructure-automation-and-programmability/data-encoding-formats/xml.md",
    "infrastructure-automation-and-programmability/data-encoding-formats/yaml.md",
    "infrastructure-automation-and-programmability/data-encoding-formats/jinja.md",
    "infrastructure-automation-and-programmability/automation-and-scripting/eem-applets.md",
    "infrastructure-automation-and-programmability/automation-and-scripting/guest-shell/linux-environment.md",
    "infrastructure-automation-and-programmability/automation-and-scripting/guest-shell/cli-python-module.md",
    "infrastructure-automation-and-programmability/automation-and-scripting/guest-shell/eem-python-module.md",
    "infrastructure-automation-and-programmability/programmability/interaction-with-vmanage-api/python-requests-library-and-postman.md",
    "infrastructure-automation-and-programmability/programmability/interaction-with-vmanage-api/monitoring-endpoints.md",
    "infrastructure-automation-and-programmability/programmability/interaction-with-vmanage-api/configuration-endpoints.md",
    "infrastructure-automation-and-programmability/programmability/interaction-with-cisco-dna-center-api.md",
    "infrastructure-automation-and-programmability/programmability/deploy-and-verify-model-driven-telemetry/configure-on-change-subscription-using-grpc.md",
]

def title_from_filename(filename):
    # Remove directory and extension, then split on dashes and capitalize each word
    base = os.path.splitext(os.path.basename(filename))[0]
    parts = base.split('-')
    return " ".join(word.capitalize() for word in parts)

# Placeholder content template
placeholder_template = """---
title: {title}
sidebar:
  open: true
---

>[!IMPORTANT]
> This content is still up in the air and has not landed on paper just yet. Stay tuned for updates, there is no estimated time frame of when this content will be written.
"""

# Path for the output ZIP file
zip_path = "ccie_docs_structure.zip"

with zipfile.ZipFile(zip_path, "w") as z:
    for file_path in files:
        title = title_from_filename(file_path)
        content_text = placeholder_template.format(title=title)
        # Write the file with the desired content into the zip archive.
        z.writestr(os.path.join("content", file_path), content_text)

print("ZIP file created at:", zip_path)

